version: "3.7"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=folk-stack-template
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:6.2.6'
    command: redis-server --requirepass kokoapps
    ports:
      - '6379:6379'
    volumes:
      - ./.cache/redis:/data

  temporalite:
    build: https://github.com/temporalio/temporalite.git#main
    ports:
      - 7233:7233
      - 8233:8233
      
